// Flat, filterable route catalog for the command palette (Section 16.2:
// "Command palette and keyboard shortcuts"). A superset of PRIMARY_NAV's
// per-section entry points, listing the actual canonical routes underneath
// each section so a keyboard/voice/switch-control user can jump straight to
// any page without navigating the sidebar tree first.
export const COMMAND_PALETTE_ROUTES: { label: string; href: string; section: string }[] = [
  { label: "Today", href: "/command/today", section: "Command Center" },
  { label: "This Week", href: "/command/week", section: "Command Center" },
  { label: "This Month", href: "/command/month", section: "Command Center" },
  { label: "This Quarter", href: "/command/quarter", section: "Command Center" },
  { label: "Annual", href: "/command/annual", section: "Command Center" },

  { label: "Roadmap Setup", href: "/roadmap/setup", section: "My Roadmap" },
  { label: "Business Command Audit", href: "/roadmap/audit", section: "My Roadmap" },
  { label: "Roadmap Plan", href: "/roadmap/plan", section: "My Roadmap" },
  { label: "Milestones", href: "/roadmap/milestones", section: "My Roadmap" },
  { label: "Gates", href: "/roadmap/gates", section: "My Roadmap" },
  { label: "Roadmap History", href: "/roadmap/history", section: "My Roadmap" },

  { label: "Founder", href: "/architecture/founder", section: "Business Architecture" },
  { label: "Strategy", href: "/architecture/strategy", section: "Business Architecture" },
  { label: "Business Model", href: "/architecture/business-model", section: "Business Architecture" },
  { label: "Market", href: "/architecture/market", section: "Business Architecture" },
  { label: "Brand", href: "/architecture/brand", section: "Business Architecture" },
  { label: "Offers", href: "/architecture/offers", section: "Business Architecture" },
  { label: "Pricing", href: "/architecture/pricing", section: "Business Architecture" },

  { label: "Revenue Overview", href: "/revenue/overview", section: "Revenue Engine" },
  { label: "Marketing", href: "/revenue/marketing", section: "Revenue Engine" },
  { label: "Content", href: "/revenue/content", section: "Revenue Engine" },
  { label: "Campaigns", href: "/revenue/campaigns", section: "Revenue Engine" },
  { label: "Outreach", href: "/revenue/outreach", section: "Revenue Engine" },
  { label: "Relationships", href: "/revenue/relationships", section: "Revenue Engine" },
  { label: "Pipeline", href: "/revenue/pipeline", section: "Revenue Engine" },
  { label: "Discovery", href: "/revenue/discovery", section: "Revenue Engine" },
  { label: "Proposals", href: "/revenue/proposals", section: "Revenue Engine" },
  { label: "Contracts", href: "/revenue/contracts", section: "Revenue Engine" },
  { label: "Payments", href: "/revenue/payments", section: "Revenue Engine" },
  { label: "Forecast", href: "/revenue/forecast", section: "Revenue Engine" },

  { label: "Clients Overview", href: "/clients/overview", section: "Client Experience" },
  { label: "Journey Design", href: "/clients/journey-design", section: "Client Experience" },
  { label: "Onboarding", href: "/clients/onboarding", section: "Client Experience" },
  { label: "Active Clients", href: "/clients/active", section: "Client Experience" },
  { label: "Programs", href: "/clients/programs", section: "Client Experience" },
  { label: "Sessions", href: "/clients/sessions", section: "Client Experience" },
  { label: "Actions", href: "/clients/actions", section: "Client Experience" },
  { label: "Outcomes", href: "/clients/outcomes", section: "Client Experience" },
  { label: "Health", href: "/clients/health", section: "Client Experience" },
  { label: "Renewals", href: "/clients/renewals", section: "Client Experience" },
  { label: "Advocacy", href: "/clients/advocacy", section: "Client Experience" },
  { label: "Client Portal", href: "/clients/portal", section: "Client Experience" },

  { label: "Operations Overview", href: "/operations/overview", section: "Operations" },
  { label: "Team", href: "/operations/team", section: "Operations" },
  { label: "Capacity", href: "/operations/capacity", section: "Operations" },
  { label: "SOPs", href: "/operations/sops", section: "Operations" },
  { label: "Automations", href: "/operations/automations", section: "Operations" },
  { label: "Finance", href: "/operations/finance", section: "Operations" },
  { label: "Legal and Risk", href: "/operations/legal-risk", section: "Operations" },
  { label: "Technology", href: "/operations/technology", section: "Operations" },
  { label: "Integrations", href: "/operations/integrations", section: "Operations" },
  { label: "Vendors", href: "/operations/vendors", section: "Operations" },

  { label: "Daily Review", href: "/reviews/daily", section: "Review Center" },
  { label: "Weekly Review", href: "/reviews/weekly", section: "Review Center" },
  { label: "Monthly Review", href: "/reviews/monthly", section: "Review Center" },
  { label: "Quarterly Review", href: "/reviews/quarterly", section: "Review Center" },
  { label: "Semiannual Review", href: "/reviews/semiannual", section: "Review Center" },
  { label: "Annual Review", href: "/reviews/annual", section: "Review Center" },
  { label: "Reports", href: "/reviews/reports", section: "Review Center" },

  { label: "AI Overview", href: "/ai/overview", section: "AI Team" },
  { label: "Agents", href: "/ai/agents", section: "AI Team" },
  { label: "Knowledge Sources", href: "/ai/knowledge", section: "AI Team" },
  { label: "Approval Queue", href: "/ai/approvals", section: "AI Team" },
  { label: "Run History", href: "/ai/runs", section: "AI Team" },
  { label: "AI Policies", href: "/ai/policies", section: "AI Team" },
  { label: "Usage and Cost", href: "/ai/usage", section: "AI Team" },

  { label: "Business Brain", href: "/library/business-brain", section: "Knowledge and Asset Library" },
  { label: "Templates", href: "/library/templates", section: "Knowledge and Asset Library" },
  { label: "Brand Library", href: "/library/brand", section: "Knowledge and Asset Library" },
  { label: "Offer Collateral", href: "/library/offers", section: "Knowledge and Asset Library" },
  { label: "Client Resources", href: "/library/client-resources", section: "Knowledge and Asset Library" },
  { label: "SOPs Index", href: "/library/sops", section: "Knowledge and Asset Library" },
  { label: "Agreements", href: "/library/agreements", section: "Knowledge and Asset Library" },
  { label: "Content Library", href: "/library/content", section: "Knowledge and Asset Library" },
  { label: "Recordings", href: "/library/recordings", section: "Knowledge and Asset Library" },
  { label: "Research Library", href: "/library/research", section: "Knowledge and Asset Library" },
  { label: "Version History", href: "/library/history", section: "Knowledge and Asset Library" },

  { label: "Work Queue", href: "/work", section: "Global" },
  { label: "Decisions", href: "/decisions", section: "Global" },
  { label: "Approvals", href: "/approvals", section: "Global" },
  { label: "Search", href: "/search", section: "Global" },
  { label: "Notifications", href: "/notifications", section: "Global" },

  { label: "Workspace", href: "/settings/workspace", section: "Settings" },
  { label: "Business Units", href: "/settings/business-units", section: "Settings" },
  { label: "Users", href: "/settings/users", section: "Settings" },
  { label: "Roles and Permissions", href: "/settings/roles", section: "Settings" },
  { label: "Settings Integrations", href: "/settings/integrations", section: "Settings" },
  { label: "Billing", href: "/settings/billing", section: "Settings" },
  { label: "Settings Notifications", href: "/settings/notifications", section: "Settings" },
  { label: "Data and Privacy", href: "/settings/data-privacy", section: "Settings" },
  { label: "Accessibility", href: "/settings/accessibility", section: "Settings" },
  { label: "Settings AI Policies", href: "/settings/ai-policies", section: "Settings" },
];
