#!/usr/bin/env python3
"""Seed generator for the canonical Business Command Audit question bank.

Reads an APPROVED, checksum-locked
src/config/business-command-audit/v<ver>/questions.json and emits a tracked SQL
migration into supabase/migrations/. It NEVER invents text — it only transcribes
approved question wording verbatim — and refuses unless the bank is approved,
checksum-matched, and structurally valid (12 phases, 48 questions, the Build
Completion / Operating Health measure pattern).

Non-destructive supersede: current Standard-template questions are reparented to
a retired template (historical audit_responses keep resolving), the Standard
template's version is bumped, and the approved bank is inserted under Standard.

Usage: python3 scripts/seed_business_command_audit.py [--version v1]
"""
import json, hashlib, os, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ver = "v1"
if "--version" in sys.argv:
    ver = sys.argv[sys.argv.index("--version") + 1]

d = os.path.join(ROOT, "src/config/business-command-audit", ver)
raw = open(os.path.join(d, "questions.json"), encoding="utf-8").read()
bank = json.loads(raw)

csum_path = os.path.join(d, "questions.checksum.txt")
if os.path.exists(csum_path):
    exp = open(csum_path).read().strip()
    act = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    if exp and exp != act:
        sys.exit(f"✗ checksum mismatch (expected {exp}, got {act}); update only if approved")

if bank.get("status") != "approved":
    sys.exit(f'✗ status is "{bank.get("status")}", not "approved"; approve the bank first')

# phaseKey -> business_command_domains.code (mostly hyphen->underscore, except marketing)
CODE = {
    "founder-leadership": "founder_leadership", "vision-strategy": "vision_strategy",
    "market-positioning": "market_positioning", "offers-pricing": "offers_pricing",
    "brand-messaging": "brand_messaging", "sales-revenue": "sales_revenue",
    "client-journey-delivery": "client_journey_delivery", "client-success-retention": "client_success_retention",
    "marketing-audience-growth": "marketing_growth", "finance-legal-risk": "finance_legal_risk",
    "operations-systems-technology": "operations_systems_technology", "team-capacity": "team_capacity",
}
MEASURE = {"Build Completion": "build_completion", "Operating Health": "operating_health"}


def sq(s):
    return "null" if s is None else "'" + s.replace("'", "''") + "'"


rows = []
for p in bank["phases"]:
    code = CODE[p["phaseKey"]]
    for q in p["questions"]:
        rows.append((
            code, q["questionKey"], q["displayOrder"], q["text"],
            MEASURE[q["primaryMeasure"]], bool(q.get("riskEligible", False)), q.get("secondaryMeasure"),
        ))
if len(rows) != 48:
    sys.exit(f"✗ expected 48 questions, got {len(rows)}")

values = ",\n".join(
    f"    (v_tpl, (select id from public.business_command_domains where code = {sq(c)}), "
    f"{sq(k)}, {do}, {sq(t)}, 'scale_0_4', {sq(sc)}, 1, {str(rk).lower()}, {sq(sm)}, false)"
    for (c, k, do, t, sc, rk, sm) in rows
)

sql = f"""-- Seed: canonical Business Command Audit question bank {ver} ({bank['version']}) — {len(rows)} questions.
-- Generated by scripts/seed_business_command_audit.py from the APPROVED,
-- checksum-locked questions.json (question text is verbatim canonical).
-- Non-destructive supersede: existing Standard-template questions are reparented
-- to a retired template so historical audit_responses keep resolving.
do $$
declare
  v_tpl uuid;
  v_retired uuid;
  v_old int;
begin
  select id into v_tpl from public.audit_templates
    where name = 'Business Command Audit — Standard' and retired_at is null
    order by version desc limit 1;
  if v_tpl is null then raise exception 'active Standard template not found'; end if;

  select count(*) into v_old from public.audit_questions where audit_template_id = v_tpl;
  if v_old > 0 then
    insert into public.audit_templates (name, version, cadence, effective_at, retired_at)
    values ('Business Command Audit — Standard — superseded ' || to_char(now(), 'YYYY-MM-DD'), 1, 'quarterly', now(), now())
    returning id into v_retired;
    update public.audit_questions set audit_template_id = v_retired where audit_template_id = v_tpl;
  end if;

  update public.audit_templates set version = version + 1 where id = v_tpl;

  insert into public.audit_questions
    (audit_template_id, domain_id, question_key, display_order, prompt, response_type, score_category, weight, risk_eligible, secondary_measure, include_in_snapshot)
  values
{values};
end $$;
"""

out = os.path.join(ROOT, "supabase/migrations", "20260721110000_seed_business_command_audit_v1.sql")
open(out, "w", encoding="utf-8").write(sql)
sys.stderr.write(f"✓ wrote {out} ({len(rows)} questions)\n")
print(sql)
